puts('Seeding Genus and Species...')
CurrentPlant.find_by_scientific_name('Grevillea pteridifolia hybrid').update(genus: 'Grevillea')
CurrentPlant.find_by_scientific_name('Scaevola \'Purple Fanfare\' (incomplete)').update(genus: 'Scaevola')
CurrentPlant.find_by_scientific_name('Arctotis x hybrida').update(genus: 'Arctotis')
CurrentPlant.find_by_scientific_name('Lobelia alata').update(genus: 'Lobelia')
CurrentPlant.find_by_scientific_name('Boronia crenulata').update(genus: 'Boronia')
CurrentPlant.find_by_scientific_name('Banksia ashbyi').update(genus: 'Banksia')
CurrentPlant.find_by_scientific_name('Viola hederacea').update(genus: 'Viola')
CurrentPlant.find_by_scientific_name('Baumea juncea').update(genus: 'Baumea')
CurrentPlant.find_by_scientific_name('Banksia baxteri (inc)').update(genus: 'Banksia')
CurrentPlant.find_by_scientific_name('Acanthus mollis').update(genus: 'Acanthus')
CurrentPlant.find_by_scientific_name('Asplenium australasicum').update(genus: 'Asplenium')
CurrentPlant.find_by_scientific_name('Macropidia fuliginosa (incomplete)').update(genus: 'Macropidia')
CurrentPlant.find_by_scientific_name('Robinia pseudoacacia').update(genus: 'Robinia')
CurrentPlant.find_by_scientific_name('Lechenaultia biloba').update(genus: 'Lechenaultia')
CurrentPlant.find_by_scientific_name('Andersonia gregoria').update(genus: 'Andersonia')
CurrentPlant.find_by_scientific_name('Euryops pectinatus').update(genus: 'Euryops')
CurrentPlant.find_by_scientific_name('Melaleuca viridiflora (incomplete)').update(genus: 'Melaleuca')
CurrentPlant.find_by_scientific_name('Melaleuca quinquenervia').update(genus: 'Melaleuca')
CurrentPlant.find_by_scientific_name('Lophostemon confertus').update(genus: 'Lophostemon')
CurrentPlant.find_by_scientific_name('Ajuga reptans').update(genus: 'Ajuga')
CurrentPlant.find_by_scientific_name('Banksia grandis').update(genus: 'Banksia')
CurrentPlant.find_by_scientific_name('Clivia miniata').update(genus: 'Clivia')
CurrentPlant.find_by_scientific_name('Pittosporum phylliraeoides (incomplete)').update(genus: 'Pittosporum')
CurrentPlant.find_by_scientific_name('Livistonia australis (incomplete)').update(genus: 'Livistonia')
CurrentPlant.find_by_scientific_name('Baeckea camphorosmae').update(genus: 'Baeckea')
CurrentPlant.find_by_scientific_name('Cinnamomum camphora').update(genus: 'Cinnamomum')
CurrentPlant.find_by_scientific_name('Phoenix canariensis').update(genus: 'Phoenix')
CurrentPlant.find_by_scientific_name('Hedera canariensis').update(genus: 'Hedera')
CurrentPlant.find_by_scientific_name('Banksia attenuata').update(genus: 'Banksia')
CurrentPlant.find_by_scientific_name('Calodendron capense').update(genus: 'Calodendron')
CurrentPlant.find_by_scientific_name('Zamia furfuracea').update(genus: 'Zamia')
CurrentPlant.find_by_scientific_name('Aspidistra elatior').update(genus: 'Aspidistra')
CurrentPlant.find_by_scientific_name('Raphiolepis indica').update(genus: 'Raphiolepis')
CurrentPlant.find_by_scientific_name('Melaleuca huegelii').update(genus: 'Melaleuca')
CurrentPlant.find_by_scientific_name('Sapium sebiferum (incomplete)').update(genus: 'Sapium')
CurrentPlant.find_by_scientific_name('Fraxinus oxycarpa cv \'Raywood\' (Incomplete)').update(genus: 'Fraxinus')
CurrentPlant.find_by_scientific_name('Olearia axillaris').update(genus: 'Olearia')
CurrentPlant.find_by_scientific_name('Eucalyptus utilis').update(genus: 'Eucalyptus')
CurrentPlant.find_by_scientific_name('Westringia fruiticosa').update(genus: 'Westringia')
CurrentPlant.find_by_scientific_name('Lepidosperma gladiatum').update(genus: 'Lepidosperma')
CurrentPlant.find_by_scientific_name('Templetonia retusa').update(genus: 'Templetonia')
CurrentPlant.find_by_scientific_name('Fraxinus excelsior (Incomplete)').update(genus: 'Fraxinus')
CurrentPlant.find_by_scientific_name('Erythrina indica').update(genus: 'Erythrina')
CurrentPlant.find_by_scientific_name('Correa reflexa').update(genus: 'Correa')
CurrentPlant.find_by_scientific_name('Dampiera linearis').update(genus: 'Dampiera')
CurrentPlant.find_by_scientific_name('Allocasuarina fraseriana').update(genus: 'Allocasuarina')
CurrentPlant.find_by_scientific_name('Conospermum stoechadis').update(genus: 'Conospermum')
CurrentPlant.find_by_scientific_name('Adenanthos cygnorum').update(genus: 'Adenanthos')
CurrentPlant.find_by_scientific_name('Acacia saligna').update(genus: 'Acacia')
CurrentPlant.find_by_scientific_name('Eucalyptus torquata').update(genus: 'Eucalyptus')
CurrentPlant.find_by_scientific_name('Cynodon dactylon').update(genus: 'Cynodon')
CurrentPlant.find_by_scientific_name('Dryandra nivea').update(genus: 'Dryandra')
CurrentPlant.find_by_scientific_name('Myoporum parvifolium').update(genus: 'Myoporum')
CurrentPlant.find_by_scientific_name('Ficus pumila').update(genus: 'Ficus')
CurrentPlant.find_by_scientific_name('Grewia occidentalis').update(genus: 'Grewia')
CurrentPlant.find_by_scientific_name('Howea belmoreana').update(genus: 'Howea')
CurrentPlant.find_by_scientific_name('Leucophyta brownii').update(genus: 'Leucophyta')
CurrentPlant.find_by_scientific_name('Brachyscome multifida').update(genus: 'Brachyscome')
CurrentPlant.find_by_scientific_name('Hibbertia cuneiformis').update(genus: 'Hibbertia')
CurrentPlant.find_by_scientific_name('Hovea pungens').update(genus: 'Hovea')
CurrentPlant.find_by_scientific_name('Coleonema pulchrum').update(genus: 'Coleonema')
CurrentPlant.find_by_scientific_name('Acacia lasiocarpa').update(genus: 'Acacia')
CurrentPlant.find_by_scientific_name('Agonis flexuosa \'nana\'').update(genus: 'Agonis')
CurrentPlant.find_by_scientific_name('Melaleuca pentagona').update(genus: 'Melaleuca')
CurrentPlant.find_by_scientific_name('Hedera helix').update(genus: 'Hedera')
CurrentPlant.find_by_scientific_name('Callistemon phoeniceus').update(genus: 'Callistemon')
CurrentPlant.find_by_scientific_name('Clivia nobilis').update(genus: 'Clivia')
CurrentPlant.find_by_scientific_name('Brachychiton acerifolius').update(genus: 'Brachychiton')
CurrentPlant.find_by_scientific_name('Acacia iteaphylla').update(genus: 'Acacia')
CurrentPlant.find_by_scientific_name('Eucalyptus rudis').update(genus: 'Eucalyptus')
CurrentPlant.find_by_scientific_name('Neurachne alopecuroides').update(genus: 'Neurachne')
CurrentPlant.find_by_scientific_name('Melaleuca rhaphiophylla').update(genus: 'Melaleuca')
CurrentPlant.find_by_scientific_name('Gazania sp.').update(genus: 'Gazania')
CurrentPlant.find_by_scientific_name('Chamelaucium uncinatum').update(genus: 'Chamelaucium')
CurrentPlant.find_by_scientific_name('Grevillea obtusifolia').update(genus: 'Grevillea')
CurrentPlant.find_by_scientific_name('Anigozanthos viridus').update(genus: 'Anigozanthos')
CurrentPlant.find_by_scientific_name('Conostylis candicans').update(genus: 'Conostylis')
CurrentPlant.find_by_scientific_name('Melaleuca incana').update(genus: 'Melaleuca')
CurrentPlant.find_by_scientific_name('Hibbertia scandens').update(genus: 'Hibbertia')
CurrentPlant.find_by_scientific_name('Eucalyptus caesia').update(genus: 'Eucalyptus')
CurrentPlant.find_by_scientific_name('Doryanthes excelsa(inc)').update(genus: 'Doryanthes')
CurrentPlant.find_by_scientific_name('Chorizema cordatum').update(genus: 'Chorizema')
CurrentPlant.find_by_scientific_name('Ficus microcarpa var. hillii (incomplete)').update(genus: 'Ficus')
CurrentPlant.find_by_scientific_name('Banksia ilicifolia').update(genus: 'Banksia')
CurrentPlant.find_by_scientific_name('Gleditsia tricanthos').update(genus: 'Gleditsia')
CurrentPlant.find_by_scientific_name('Banksia hookeriana').update(genus: 'Banksia')
CurrentPlant.find_by_scientific_name('Casuarina equisetifolia').update(genus: 'Casuarina')
CurrentPlant.find_by_scientific_name('Eucalyptus erythrocorys').update(genus: 'Eucalyptus')
CurrentPlant.find_by_scientific_name('Cupressus sempervirens').update(genus: 'Cupressus')
CurrentPlant.find_by_scientific_name('Jacaranda mimosifolia').update(genus: 'Jacaranda')
CurrentPlant.find_by_scientific_name('Parthenocissus tricuspidata (incomplete)').update(genus: 'Parthenocissus')
CurrentPlant.find_by_scientific_name('Eucalyptus marginata').update(genus: 'Eucalyptus')
CurrentPlant.find_by_scientific_name('Baumea articulata').update(genus: 'Baumea')
CurrentPlant.find_by_scientific_name('Howea forsteriana (incomplete)').update(genus: 'Howea')
CurrentPlant.find_by_scientific_name('Dichondra repens').update(genus: 'Dichondra')
CurrentPlant.find_by_scientific_name('Kingia australis').update(genus: 'Kingia')
CurrentPlant.find_by_scientific_name('Ficinia nodosa').update(genus: 'Ficinia')
CurrentPlant.find_by_scientific_name('Cyathea cooperi').update(genus: 'Cyathea')
CurrentPlant.find_by_scientific_name('Darwinia citriodora').update(genus: 'Darwinia')
CurrentPlant.find_by_scientific_name('Corymbia citriodora').update(genus: 'Corymbia')
CurrentPlant.find_by_scientific_name('Acmena smithii').update(genus: 'Acmena')
CurrentPlant.find_by_scientific_name('Liquidamber styraciflua (incomplete)').update(genus: 'Liquidamber')
CurrentPlant.find_by_scientific_name('Plantanus x acerfolia').update(genus: 'Plantanus')
CurrentPlant.find_by_scientific_name('Macadamia tetraphylla (incomplete)').update(genus: 'Macadamia')
CurrentPlant.find_by_scientific_name('Ginkgo biloba').update(genus: 'Ginkgo')
CurrentPlant.find_by_scientific_name('Corymbia calophylla').update(genus: 'Corymbia')
CurrentPlant.find_by_scientific_name('Banksia menziesii').update(genus: 'Banksia')
CurrentPlant.find_by_scientific_name('Ficus macrophylla').update(genus: 'Ficus')
CurrentPlant.find_by_scientific_name('Convolvulus sabatius').update(genus: 'Convolvulus')
CurrentPlant.find_by_scientific_name('Eucalyptus macrocarpa').update(genus: 'Eucalyptus')
CurrentPlant.find_by_scientific_name('Acacia aneura').update(genus: 'Acacia')
CurrentPlant.find_by_scientific_name('Pilots exaltatus').update(genus: 'Pilots')
CurrentPlant.find_by_scientific_name('Hymenosporum flavum').update(genus: 'Hymenosporum')
CurrentPlant.find_by_scientific_name('Carpobrotus virescens').update(genus: 'Carpobrotus')
CurrentPlant.find_by_scientific_name('Hardenbergia comptoniana').update(genus: 'Hardenbergia')
CurrentPlant.find_by_scientific_name('Araucaria heterophylla').update(genus: 'Araucaria')
CurrentPlant.find_by_scientific_name('Ceratoptalum gummiferum').update(genus: 'Ceratoptalum')
CurrentPlant.find_by_scientific_name('Clematis microphylla').update(genus: 'Clematis')
CurrentPlant.find_by_scientific_name('Grevillea leucopteris [incomplete]').update(genus: 'Grevillea')
CurrentPlant.find_by_scientific_name('Calothamnus quadrifidus').update(genus: 'Calothamnus')
CurrentPlant.find_by_scientific_name('Eremaea pauciflora').update(genus: 'Eremaea')
CurrentPlant.find_by_scientific_name('Murraya paniculata').update(genus: 'Murraya')
CurrentPlant.find_by_scientific_name('Dryandra sessilis').update(genus: 'Dryandra')
CurrentPlant.find_by_scientific_name('Agonis flexuosa').update(genus: 'Agonis')
CurrentPlant.find_by_scientific_name('Carpobrotus glaucescens').update(genus: 'Carpobrotus')
CurrentPlant.find_by_scientific_name('Aptenia cordifolia').update(genus: 'Aptenia')
CurrentPlant.find_by_scientific_name('Hakea laurina').update(genus: 'Hakea')
CurrentPlant.find_by_scientific_name('Pimelea ferruginea').update(genus: 'Pimelea')
CurrentPlant.find_by_scientific_name('Eucalyptus sideroxylon').update(genus: 'Eucalyptus')
CurrentPlant.find_by_scientific_name('Podocarpus elatus (incomplete)').update(genus: 'Podocarpus')
CurrentPlant.find_by_scientific_name('Delonix regia').update(genus: 'Delonix')
CurrentPlant.find_by_scientific_name('Ficus rubiginosa').update(genus: 'Ficus')
CurrentPlant.find_by_scientific_name('Acacia pulchella').update(genus: 'Acacia')
CurrentPlant.find_by_scientific_name('Tipuana tipu').update(genus: 'Tipuana')
CurrentPlant.find_by_scientific_name('Phoenix roebelenii').update(genus: 'Phoenix')
CurrentPlant.find_by_scientific_name('Pittosporum rhombifolium (incomplete)').update(genus: 'Pittosporum')
CurrentPlant.find_by_scientific_name('Acacia acuminata').update(genus: 'Acacia')
CurrentPlant.find_by_scientific_name('Anigozanthos manglesii').update(genus: 'Anigozanthos')
CurrentPlant.find_by_scientific_name('Boronia heterophylla').update(genus: 'Boronia')
CurrentPlant.find_by_scientific_name('Syncarpia glomifera').update(genus: 'Syncarpia')
CurrentPlant.find_by_scientific_name('Acacia cyclops').update(genus: 'Acacia')
CurrentPlant.find_by_scientific_name('Corymbia ficifolia').update(genus: 'Corymbia')
CurrentPlant.find_by_scientific_name('Casuarina cunninghamiana').update(genus: 'Casuarina')
CurrentPlant.find_by_scientific_name('Eucalyptus camaldulensis').update(genus: 'Eucalyptus')
CurrentPlant.find_by_scientific_name('Grevillea rosmarinifolia').update(genus: 'Grevillea')
CurrentPlant.find_by_scientific_name('Callitris preissii').update(genus: 'Callitris')
CurrentPlant.find_by_scientific_name('Melaleuca lanceolata').update(genus: 'Melaleuca')
CurrentPlant.find_by_scientific_name('Casuarina obesa').update(genus: 'Casuarina')
CurrentPlant.find_by_scientific_name('Melaleuca cuticularis').update(genus: 'Melaleuca')
CurrentPlant.find_by_scientific_name('Beaufortia squarrosa').update(genus: 'Beaufortia')
CurrentPlant.find_by_scientific_name('Banksia prionotes').update(genus: 'Banksia')
CurrentPlant.find_by_scientific_name('Banksia coccinea').update(genus: 'Banksia')
CurrentPlant.find_by_scientific_name('Juncus karusii (incomplete)').update(genus: 'Juncus')
CurrentPlant.find_by_scientific_name('Hakea petiolaris').update(genus: 'Hakea')
CurrentPlant.find_by_scientific_name('Melaleuca nesophila').update(genus: 'Melaleuca')
CurrentPlant.find_by_scientific_name('Eremophila nivea').update(genus: 'Eremophila')
CurrentPlant.find_by_scientific_name('Cymbopogon obtectus').update(genus: 'Cymbopogon')
CurrentPlant.find_by_scientific_name('Grevillea robusta').update(genus: 'Grevillea')
CurrentPlant.find_by_scientific_name('Senna artemisioides').update(genus: 'Senna')
CurrentPlant.find_by_scientific_name('Angophora costata').update(genus: 'Angophora')
CurrentPlant.find_by_scientific_name('Hemiandra pungens').update(genus: 'Hemiandra')
CurrentPlant.find_by_scientific_name('Grevillea thelemanniana').update(genus: 'Grevillea')
CurrentPlant.find_by_scientific_name('Grevillea preisii \'Grevillea thelemanniana').update(genus: 'Grevillea')
CurrentPlant.find_by_scientific_name('Chlorophytum comosum').update(genus: 'Chlorophytum')
CurrentPlant.find_by_scientific_name('Lomandra longifolia').update(genus: 'Lomandra')
CurrentPlant.find_by_scientific_name('Corymbia maculata').update(genus: 'Corymbia')
CurrentPlant.find_by_scientific_name('Dianella revoluta').update(genus: 'Dianella')
CurrentPlant.find_by_scientific_name('Eucalyptus cladocalyx').update(genus: 'Eucalyptus')
CurrentPlant.find_by_scientific_name('Banksia littoralis').update(genus: 'Banksia')
CurrentPlant.find_by_scientific_name('Crinum pedunculatum').update(genus: 'Crinum')
CurrentPlant.find_by_scientific_name('Agonis linearifolia').update(genus: 'Agonis')
CurrentPlant.find_by_scientific_name('Brachyscome iberidifolia').update(genus: 'Brachyscome')
CurrentPlant.find_by_scientific_name('Hypocalymma robustum').update(genus: 'Hypocalymma')
CurrentPlant.find_by_scientific_name('Thryptomene saxicola (incomplete)').update(genus: 'Thryptomene')
CurrentPlant.find_by_scientific_name('Eremophila glabra').update(genus: 'Eremophila')
CurrentPlant.find_by_scientific_name('Coprosma repens').update(genus: 'Coprosma')
CurrentPlant.find_by_scientific_name('Scaevola crassifolia').update(genus: 'Scaevola')
CurrentPlant.find_by_scientific_name('Hovea elliptica').update(genus: 'Hovea')
CurrentPlant.find_by_scientific_name('Eucalyptus gomphocephala').update(genus: 'Eucalyptus')
CurrentPlant.find_by_scientific_name('Parthenocissus quiniquefolia (incomplete)').update(genus: 'Parthenocissus')
CurrentPlant.find_by_scientific_name('Eucalyptus wandoo').update(genus: 'Eucalyptus')
CurrentPlant.find_by_scientific_name('Chamelaucium ciliatum').update(genus: 'Chamelaucium')
CurrentPlant.find_by_scientific_name('Ricinocarpus tuberculatus x cyanescens').update(genus: 'Ricinocarpus')
CurrentPlant.find_by_scientific_name('Callistemon viminalis').update(genus: 'Callistemon')
CurrentPlant.find_by_scientific_name('Melaleuca leucadendra').update(genus: 'Melaleuca')
CurrentPlant.find_by_scientific_name('Baeckea virgata (inc)').update(genus: 'Baeckea')
CurrentPlant.find_by_scientific_name('Melia azedarach var. australasica (incomplete)').update(genus: 'Melia')
CurrentPlant.find_by_scientific_name('Brachychiton discolour').update(genus: 'Brachychiton')
CurrentPlant.find_by_scientific_name('Acacia xanthina').update(genus: 'Acacia')
CurrentPlant.find_by_scientific_name('Dietes grandiflora').update(genus: 'Dietes')
CurrentPlant.find_by_scientific_name('Wollemia nobilis').update(genus: 'Wollemia')
CurrentPlant.find_by_scientific_name('Banksia victoriae').update(genus: 'Banksia')
CurrentPlant.find_by_scientific_name('Adenanthos sericeus').update(genus: 'Adenanthos')
CurrentPlant.find_by_scientific_name('Helichrysum ramosissimum (incomplete)').update(genus: 'Helichrysum')
CurrentPlant.find_by_scientific_name('Eucalyptus leucoxylon').update(genus: 'Eucalyptus')
CurrentPlant.find_by_scientific_name('Anigozanthos flavidus').update(genus: 'Anigozanthos')
CurrentPlant.find_by_scientific_name('Brunfelsia pauciflora').update(genus: 'Brunfelsia')
CurrentPlant.find_by_scientific_name('Verticordia nitens').update(genus: 'Verticordia')
CurrentPlant.find_by_scientific_name('Bougainvillea glabra').update(genus: 'Bougainvillea')
CurrentPlant.find_by_scientific_name('Astartea fascicularis').update(genus: 'Astartea')
CurrentPlant.find_by_scientific_name('Grevillea \'Poorinda Royal Mantle\' (incomplete)').update(genus: 'Grevillea')
CurrentPlant.find_by_scientific_name('Maireana oppositifolia').update(genus: 'Maireana')
CurrentPlant.find_by_scientific_name('Callistemon Little John').update(genus: 'Callistemon')
CurrentPlant.find_by_scientific_name('Rhagodia  spinescens var deltophylla').update(genus: 'Rhagodia')
CurrentPlant.find_by_scientific_name('Verticordia monadelpha').update(genus: 'Verticordia')
CurrentPlant.find_by_scientific_name('Nerium oleander cv pink Surprise').update(genus: 'Nerium')
CurrentPlant.find_by_scientific_name('Cordyline australis (inc)').update(genus: 'Cordyline')
CurrentPlant.find_by_scientific_name('Banksia gardneri').update(genus: 'Banksia')
CurrentPlant.find_by_scientific_name('Dietes bicolor').update(genus: 'Dietes')
CurrentPlant.find_by_scientific_name('Dietes iridioides').update(genus: 'Dietes')
CurrentPlant.find_by_scientific_name('Spinifex hirsutus').update(genus: 'Spinifex')
CurrentPlant.find_by_scientific_name('Spinifex longifolia').update(genus: 'Spinifex')
CurrentPlant.find_by_scientific_name('Agapanthus praecox').update(genus: 'Agapanthus')
CurrentPlant.find_by_scientific_name('Banksia blechnifolia (incomplete)').update(genus: 'Banksia')
CurrentPlant.find_by_scientific_name('Banksia petiolaris').update(genus: 'Banksia')
CurrentPlant.find_by_scientific_name('Hibbertia huegelii').update(genus: 'Hibbertia')
CurrentPlant.find_by_scientific_name('Correa alba').update(genus: 'Correa')
CurrentPlant.find_by_scientific_name('Guichenotia ledifolia').update(genus: 'Guichenotia')
CurrentPlant.find_by_scientific_name('Calothamnus hirsutus').update(genus: 'Calothamnus')
CurrentPlant.find_by_scientific_name('Acacia rostellifera').update(genus: 'Acacia')
CurrentPlant.find_by_scientific_name('Acacia truncata (incomplete)').update(genus: 'Acacia')
CurrentPlant.find_by_scientific_name('Banksia ericifolia').update(genus: 'Banksia')
CurrentPlant.find_by_scientific_name('Cordyline indivisa').update(genus: 'Cordyline')
CurrentPlant.find_by_scientific_name('Cycad thouarsi').update(genus: 'Cycad')
CurrentPlant.find_by_scientific_name('Dodonea viscosa purpurea').update(genus: 'Dodonea')
CurrentPlant.find_by_scientific_name('Eremophila ?').update(genus: 'Eremophila')
CurrentPlant.find_by_scientific_name('Eremophila 2').update(genus: 'Eremophila')
CurrentPlant.find_by_scientific_name('Eucalyptus foecunda').update(genus: 'Eucalyptus')
CurrentPlant.find_by_scientific_name('Eucalyptus Lemanii').update(genus: 'Eucalyptus')
CurrentPlant.find_by_scientific_name('Eucalyptus tetragona (incomplete)').update(genus: 'Eucalyptus')
CurrentPlant.find_by_scientific_name('Grevillea \'Robyn Gordon\'').update(genus: 'Grevillea')
CurrentPlant.find_by_scientific_name('Grevillea crithmifolia').update(genus: 'Grevillea')
CurrentPlant.find_by_scientific_name('Grevillea nudiflora').update(genus: 'Grevillea')
CurrentPlant.find_by_scientific_name('Grevillea olivacea [inc]').update(genus: 'Grevillea')
CurrentPlant.find_by_scientific_name('Hake 1').update(genus: 'Hake')
CurrentPlant.find_by_scientific_name('Hake 2').update(genus: 'Hake')
CurrentPlant.find_by_scientific_name('Juncus pallidus').update(genus: 'Juncus')
CurrentPlant.find_by_scientific_name('Raphiolepis cv Apple Blossum').update(genus: 'Raphiolepis')
CurrentPlant.find_by_scientific_name('Scaffold aneura').update(genus: 'Scaffold')
CurrentPlant.find_by_scientific_name('Tecoma alata').update(genus: 'Tecoma')
CurrentPlant.find_by_scientific_name('Tetragona decumbens').update(genus: 'Tetragona')
CurrentPlant.find_by_scientific_name('Unknown 2').update(genus: 'Unknown')
CurrentPlant.find_by_scientific_name('Unknown 3').update(genus: 'Unknown')
CurrentPlant.find_by_scientific_name('Water hyacinth').update(genus: 'Water')
CurrentPlant.find_by_scientific_name('Yellow Broome').update(genus: 'Yellow')
CurrentPlant.find_by_scientific_name('Grevillea pteridifolia hybrid').update(species: 'pteridifolia hybrid')
CurrentPlant.find_by_scientific_name('Arctotis x hybrida').update(species: 'x hybrida')
CurrentPlant.find_by_scientific_name('Lobelia alata').update(species: 'alata')
CurrentPlant.find_by_scientific_name('Boronia crenulata').update(species: 'crenulata')
CurrentPlant.find_by_scientific_name('Banksia ashbyi').update(species: 'ashbyi')
CurrentPlant.find_by_scientific_name('Viola hederacea').update(species: 'hederacea')
CurrentPlant.find_by_scientific_name('Baumea juncea').update(species: 'juncea')
CurrentPlant.find_by_scientific_name('Banksia baxteri (inc)').update(species: 'baxteri ')
CurrentPlant.find_by_scientific_name('Acanthus mollis').update(species: 'mollis')
CurrentPlant.find_by_scientific_name('Asplenium australasicum').update(species: 'australasicum')
CurrentPlant.find_by_scientific_name('Macropidia fuliginosa (incomplete)').update(species: 'fuliginosa')
CurrentPlant.find_by_scientific_name('Robinia pseudoacacia').update(species: 'pseudoacacia')
CurrentPlant.find_by_scientific_name('Lechenaultia biloba').update(species: 'biloba')
CurrentPlant.find_by_scientific_name('Andersonia gregoria').update(species: 'gregoria')
CurrentPlant.find_by_scientific_name('Euryops pectinatus').update(species: 'pectinatus')
CurrentPlant.find_by_scientific_name('Melaleuca viridiflora (incomplete)').update(species: 'viridiflora ')
CurrentPlant.find_by_scientific_name('Melaleuca quinquenervia').update(species: 'quinquenervia')
CurrentPlant.find_by_scientific_name('Lophostemon confertus').update(species: 'confertus')
CurrentPlant.find_by_scientific_name('Ajuga reptans').update(species: 'reptans')
CurrentPlant.find_by_scientific_name('Banksia grandis').update(species: 'grandis')
CurrentPlant.find_by_scientific_name('Clivia miniata').update(species: 'miniata')
CurrentPlant.find_by_scientific_name('Pittosporum phylliraeoides (incomplete)').update(species: 'phylliraeoides ')
CurrentPlant.find_by_scientific_name('Livistonia australis (incomplete)').update(species: 'australis ')
CurrentPlant.find_by_scientific_name('Baeckea camphorosmae').update(species: 'camphorosmae')
CurrentPlant.find_by_scientific_name('Cinnamomum camphora').update(species: 'camphora')
CurrentPlant.find_by_scientific_name('Phoenix canariensis').update(species: 'canariensis')
CurrentPlant.find_by_scientific_name('Hedera canariensis').update(species: 'canariensis')
CurrentPlant.find_by_scientific_name('Banksia attenuata').update(species: 'attenuata')
CurrentPlant.find_by_scientific_name('Calodendron capense').update(species: 'capense')
CurrentPlant.find_by_scientific_name('Zamia furfuracea').update(species: 'furfuracea')
CurrentPlant.find_by_scientific_name('Aspidistra elatior').update(species: 'elatior')
CurrentPlant.find_by_scientific_name('Raphiolepis indica').update(species: 'indica')
CurrentPlant.find_by_scientific_name('Melaleuca huegelii').update(species: 'huegelii')
CurrentPlant.find_by_scientific_name('Sapium sebiferum (incomplete)').update(species: 'sebiferum ')
CurrentPlant.find_by_scientific_name('Fraxinus oxycarpa cv \'Raywood\' (Incomplete)').update(species: 'oxycarpa cv \'Raywood\' (Incomplete)')
CurrentPlant.find_by_scientific_name('Olearia axillaris').update(species: 'axillaris')
CurrentPlant.find_by_scientific_name('Eucalyptus utilis').update(species: 'utilis')
CurrentPlant.find_by_scientific_name('Westringia fruiticosa').update(species: 'fruiticosa')
CurrentPlant.find_by_scientific_name('Lepidosperma gladiatum').update(species: 'gladiatum')
CurrentPlant.find_by_scientific_name('Templetonia retusa').update(species: 'retusa')
CurrentPlant.find_by_scientific_name('Fraxinus excelsior (Incomplete)').update(species: 'excelsior (Incomplete)')
CurrentPlant.find_by_scientific_name('Erythrina indica').update(species: 'indica')
CurrentPlant.find_by_scientific_name('Correa reflexa').update(species: 'reflexa')
CurrentPlant.find_by_scientific_name('Dampiera linearis').update(species: 'linearis')
CurrentPlant.find_by_scientific_name('Allocasuarina fraseriana').update(species: 'fraseriana')
CurrentPlant.find_by_scientific_name('Conospermum stoechadis').update(species: 'stoechadis')
CurrentPlant.find_by_scientific_name('Adenanthos cygnorum').update(species: 'cygnorum')
CurrentPlant.find_by_scientific_name('Acacia saligna').update(species: 'saligna')
CurrentPlant.find_by_scientific_name('Eucalyptus torquata').update(species: 'torquata')
CurrentPlant.find_by_scientific_name('Cynodon dactylon').update(species: 'dactylon')
CurrentPlant.find_by_scientific_name('Dryandra nivea').update(species: 'nivea')
CurrentPlant.find_by_scientific_name('Myoporum parvifolium').update(species: 'parvifolium')
CurrentPlant.find_by_scientific_name('Ficus pumila').update(species: 'pumila')
CurrentPlant.find_by_scientific_name('Grewia occidentalis').update(species: 'occidentalis')
CurrentPlant.find_by_scientific_name('Howea belmoreana').update(species: 'belmoreana')
CurrentPlant.find_by_scientific_name('Leucophyta brownii').update(species: 'brownii')
CurrentPlant.find_by_scientific_name('Brachyscome multifida').update(species: 'multifida')
CurrentPlant.find_by_scientific_name('Hibbertia cuneiformis').update(species: 'cuneiformis')
CurrentPlant.find_by_scientific_name('Hovea pungens').update(species: 'pungens')
CurrentPlant.find_by_scientific_name('Coleonema pulchrum').update(species: 'pulchrum')
CurrentPlant.find_by_scientific_name('Acacia lasiocarpa').update(species: 'lasiocarpa')
CurrentPlant.find_by_scientific_name('Agonis flexuosa \'nana\'').update(species: 'flexuosa \'nana\'')
CurrentPlant.find_by_scientific_name('Melaleuca pentagona').update(species: 'pentagona')
CurrentPlant.find_by_scientific_name('Hedera helix').update(species: 'helix')
CurrentPlant.find_by_scientific_name('Callistemon phoeniceus').update(species: 'phoeniceus')
CurrentPlant.find_by_scientific_name('Clivia nobilis').update(species: 'nobilis')
CurrentPlant.find_by_scientific_name('Brachychiton acerifolius').update(species: 'acerifolius')
CurrentPlant.find_by_scientific_name('Acacia iteaphylla').update(species: 'iteaphylla')
CurrentPlant.find_by_scientific_name('Eucalyptus rudis').update(species: 'rudis')
CurrentPlant.find_by_scientific_name('Neurachne alopecuroides').update(species: 'alopecuroides')
CurrentPlant.find_by_scientific_name('Melaleuca rhaphiophylla').update(species: 'rhaphiophylla')
CurrentPlant.find_by_scientific_name('Gazania sp.').update(species: 'sp.')
CurrentPlant.find_by_scientific_name('Chamelaucium uncinatum').update(species: 'uncinatum')
CurrentPlant.find_by_scientific_name('Grevillea obtusifolia').update(species: 'obtusifolia')
CurrentPlant.find_by_scientific_name('Anigozanthos viridus').update(species: 'viridus')
CurrentPlant.find_by_scientific_name('Conostylis candicans').update(species: 'candicans')
CurrentPlant.find_by_scientific_name('Melaleuca incana').update(species: 'incana')
CurrentPlant.find_by_scientific_name('Hibbertia scandens').update(species: 'scandens')
CurrentPlant.find_by_scientific_name('Eucalyptus caesia').update(species: 'caesia')
CurrentPlant.find_by_scientific_name('Doryanthes excelsa(inc)').update(species: 'excelsa')
CurrentPlant.find_by_scientific_name('Chorizema cordatum').update(species: 'cordatum')
CurrentPlant.find_by_scientific_name('Ficus microcarpa var. hillii (incomplete)').update(species: 'microcarpa var. hillii ')
CurrentPlant.find_by_scientific_name('Banksia ilicifolia').update(species: 'ilicifolia')
CurrentPlant.find_by_scientific_name('Gleditsia tricanthos').update(species: 'tricanthos')
CurrentPlant.find_by_scientific_name('Banksia hookeriana').update(species: 'hookeriana')
CurrentPlant.find_by_scientific_name('Casuarina equisetifolia').update(species: 'equisetifolia')
CurrentPlant.find_by_scientific_name('Eucalyptus erythrocorys').update(species: 'erythrocorys')
CurrentPlant.find_by_scientific_name('Cupressus sempervirens').update(species: 'sempervirens')
CurrentPlant.find_by_scientific_name('Jacaranda mimosifolia').update(species: 'mimosifolia')
CurrentPlant.find_by_scientific_name('Parthenocissus tricuspidata (incomplete)').update(species: 'tricuspidata ')
CurrentPlant.find_by_scientific_name('Eucalyptus marginata').update(species: 'marginata')
CurrentPlant.find_by_scientific_name('Baumea articulata').update(species: 'articulata')
CurrentPlant.find_by_scientific_name('Howea forsteriana (incomplete)').update(species: 'forsteriana ')
CurrentPlant.find_by_scientific_name('Dichondra repens').update(species: 'repens')
CurrentPlant.find_by_scientific_name('Kingia australis').update(species: 'australis')
CurrentPlant.find_by_scientific_name('Ficinia nodosa').update(species: 'nodosa')
CurrentPlant.find_by_scientific_name('Cyathea cooperi').update(species: 'cooperi')
CurrentPlant.find_by_scientific_name('Darwinia citriodora').update(species: 'citriodora')
CurrentPlant.find_by_scientific_name('Corymbia citriodora').update(species: 'citriodora')
CurrentPlant.find_by_scientific_name('Acmena smithii').update(species: 'smithii')
CurrentPlant.find_by_scientific_name('Liquidamber styraciflua (incomplete)').update(species: 'styraciflua ')
CurrentPlant.find_by_scientific_name('Plantanus x acerfolia').update(species: 'x acerfolia')
CurrentPlant.find_by_scientific_name('Macadamia tetraphylla (incomplete)').update(species: 'tetraphylla ')
CurrentPlant.find_by_scientific_name('Ginkgo biloba').update(species: 'biloba')
CurrentPlant.find_by_scientific_name('Corymbia calophylla').update(species: 'calophylla')
CurrentPlant.find_by_scientific_name('Banksia menziesii').update(species: 'menziesii')
CurrentPlant.find_by_scientific_name('Ficus macrophylla').update(species: 'macrophylla')
CurrentPlant.find_by_scientific_name('Convolvulus sabatius').update(species: 'sabatius')
CurrentPlant.find_by_scientific_name('Eucalyptus macrocarpa').update(species: 'macrocarpa')
CurrentPlant.find_by_scientific_name('Acacia aneura').update(species: 'aneura')
CurrentPlant.find_by_scientific_name('Pilots exaltatus').update(species: 'exaltatus')
CurrentPlant.find_by_scientific_name('Hymenosporum flavum').update(species: 'flavum')
CurrentPlant.find_by_scientific_name('Carpobrotus virescens').update(species: 'virescens')
CurrentPlant.find_by_scientific_name('Hardenbergia comptoniana').update(species: 'comptoniana')
CurrentPlant.find_by_scientific_name('Araucaria heterophylla').update(species: 'heterophylla')
CurrentPlant.find_by_scientific_name('Ceratoptalum gummiferum').update(species: 'gummiferum')
CurrentPlant.find_by_scientific_name('Clematis microphylla').update(species: 'microphylla')
CurrentPlant.find_by_scientific_name('Grevillea leucopteris [incomplete]').update(species: 'leucopteris [incomplete]')
CurrentPlant.find_by_scientific_name('Calothamnus quadrifidus').update(species: 'quadrifidus')
CurrentPlant.find_by_scientific_name('Eremaea pauciflora').update(species: 'pauciflora')
CurrentPlant.find_by_scientific_name('Murraya paniculata').update(species: 'paniculata')
CurrentPlant.find_by_scientific_name('Dryandra sessilis').update(species: 'sessilis')
CurrentPlant.find_by_scientific_name('Agonis flexuosa').update(species: 'flexuosa')
CurrentPlant.find_by_scientific_name('Carpobrotus glaucescens').update(species: 'glaucescens')
CurrentPlant.find_by_scientific_name('Aptenia cordifolia').update(species: 'cordifolia')
CurrentPlant.find_by_scientific_name('Hakea laurina').update(species: 'laurina')
CurrentPlant.find_by_scientific_name('Pimelea ferruginea').update(species: 'ferruginea')
CurrentPlant.find_by_scientific_name('Eucalyptus sideroxylon').update(species: 'sideroxylon')
CurrentPlant.find_by_scientific_name('Podocarpus elatus (incomplete)').update(species: 'elatus ')
CurrentPlant.find_by_scientific_name('Delonix regia').update(species: 'regia')
CurrentPlant.find_by_scientific_name('Ficus rubiginosa').update(species: 'rubiginosa')
CurrentPlant.find_by_scientific_name('Acacia pulchella').update(species: 'pulchella')
CurrentPlant.find_by_scientific_name('Tipuana tipu').update(species: 'tipu')
CurrentPlant.find_by_scientific_name('Phoenix roebelenii').update(species: 'roebelenii')
CurrentPlant.find_by_scientific_name('Pittosporum rhombifolium (incomplete)').update(species: 'rhombifolium ')
CurrentPlant.find_by_scientific_name('Acacia acuminata').update(species: 'acuminata')
CurrentPlant.find_by_scientific_name('Anigozanthos manglesii').update(species: 'manglesii')
CurrentPlant.find_by_scientific_name('Boronia heterophylla').update(species: 'heterophylla')
CurrentPlant.find_by_scientific_name('Syncarpia glomifera').update(species: 'glomifera')
CurrentPlant.find_by_scientific_name('Acacia cyclops').update(species: 'cyclops')
CurrentPlant.find_by_scientific_name('Corymbia ficifolia').update(species: 'ficifolia')
CurrentPlant.find_by_scientific_name('Casuarina cunninghamiana').update(species: 'cunninghamiana')
CurrentPlant.find_by_scientific_name('Eucalyptus camaldulensis').update(species: 'camaldulensis')
CurrentPlant.find_by_scientific_name('Grevillea rosmarinifolia').update(species: 'rosmarinifolia')
CurrentPlant.find_by_scientific_name('Callitris preissii').update(species: 'preissii')
CurrentPlant.find_by_scientific_name('Melaleuca lanceolata').update(species: 'lanceolata')
CurrentPlant.find_by_scientific_name('Casuarina obesa').update(species: 'obesa')
CurrentPlant.find_by_scientific_name('Melaleuca cuticularis').update(species: 'cuticularis')
CurrentPlant.find_by_scientific_name('Beaufortia squarrosa').update(species: 'squarrosa')
CurrentPlant.find_by_scientific_name('Banksia prionotes').update(species: 'prionotes')
CurrentPlant.find_by_scientific_name('Banksia coccinea').update(species: 'coccinea')
CurrentPlant.find_by_scientific_name('Juncus karusii (incomplete)').update(species: 'karusii ')
CurrentPlant.find_by_scientific_name('Hakea petiolaris').update(species: 'petiolaris')
CurrentPlant.find_by_scientific_name('Melaleuca nesophila').update(species: 'nesophila')
CurrentPlant.find_by_scientific_name('Eremophila nivea').update(species: 'nivea')
CurrentPlant.find_by_scientific_name('Cymbopogon obtectus').update(species: 'obtectus')
CurrentPlant.find_by_scientific_name('Grevillea robusta').update(species: 'robusta')
CurrentPlant.find_by_scientific_name('Senna artemisioides').update(species: 'artemisioides')
CurrentPlant.find_by_scientific_name('Angophora costata').update(species: 'costata')
CurrentPlant.find_by_scientific_name('Hemiandra pungens').update(species: 'pungens')
CurrentPlant.find_by_scientific_name('Grevillea thelemanniana').update(species: 'thelemanniana')
CurrentPlant.find_by_scientific_name('Grevillea preisii \'Grevillea thelemanniana').update(species: 'preisii \'Grevillea thelemanniana')
CurrentPlant.find_by_scientific_name('Chlorophytum comosum').update(species: 'comosum')
CurrentPlant.find_by_scientific_name('Lomandra longifolia').update(species: 'longifolia')
CurrentPlant.find_by_scientific_name('Corymbia maculata').update(species: 'maculata')
CurrentPlant.find_by_scientific_name('Dianella revoluta').update(species: 'revoluta')
CurrentPlant.find_by_scientific_name('Eucalyptus cladocalyx').update(species: 'cladocalyx')
CurrentPlant.find_by_scientific_name('Banksia littoralis').update(species: 'littoralis')
CurrentPlant.find_by_scientific_name('Crinum pedunculatum').update(species: 'pedunculatum')
CurrentPlant.find_by_scientific_name('Agonis linearifolia').update(species: 'linearifolia')
CurrentPlant.find_by_scientific_name('Brachyscome iberidifolia').update(species: 'iberidifolia')
CurrentPlant.find_by_scientific_name('Hypocalymma robustum').update(species: 'robustum')
CurrentPlant.find_by_scientific_name('Thryptomene saxicola (incomplete)').update(species: 'saxicola ')
CurrentPlant.find_by_scientific_name('Eremophila glabra').update(species: 'glabra')
CurrentPlant.find_by_scientific_name('Coprosma repens').update(species: 'repens')
CurrentPlant.find_by_scientific_name('Scaevola crassifolia').update(species: 'crassifolia')
CurrentPlant.find_by_scientific_name('Hovea elliptica').update(species: 'elliptica')
CurrentPlant.find_by_scientific_name('Eucalyptus gomphocephala').update(species: 'gomphocephala')
CurrentPlant.find_by_scientific_name('Parthenocissus quiniquefolia (incomplete)').update(species: 'quiniquefolia ')
CurrentPlant.find_by_scientific_name('Eucalyptus wandoo').update(species: 'wandoo')
CurrentPlant.find_by_scientific_name('Chamelaucium ciliatum').update(species: 'ciliatum')
CurrentPlant.find_by_scientific_name('Ricinocarpus tuberculatus x cyanescens').update(species: 'tuberculatus x cyanescens')
CurrentPlant.find_by_scientific_name('Callistemon viminalis').update(species: 'viminalis')
CurrentPlant.find_by_scientific_name('Melaleuca leucadendra').update(species: 'leucadendra')
CurrentPlant.find_by_scientific_name('Baeckea virgata (inc)').update(species: 'virgata ')
CurrentPlant.find_by_scientific_name('Melia azedarach var. australasica (incomplete)').update(species: 'azedarach var. australasica ')
CurrentPlant.find_by_scientific_name('Brachychiton discolour').update(species: 'discolour')
CurrentPlant.find_by_scientific_name('Acacia xanthina').update(species: 'xanthina')
CurrentPlant.find_by_scientific_name('Dietes grandiflora').update(species: 'grandiflora')
CurrentPlant.find_by_scientific_name('Wollemia nobilis').update(species: 'nobilis')
CurrentPlant.find_by_scientific_name('Banksia victoriae').update(species: 'victoriae')
CurrentPlant.find_by_scientific_name('Adenanthos sericeus').update(species: 'sericeus')
CurrentPlant.find_by_scientific_name('Helichrysum ramosissimum (incomplete)').update(species: 'ramosissimum ')
CurrentPlant.find_by_scientific_name('Eucalyptus leucoxylon').update(species: 'leucoxylon')
CurrentPlant.find_by_scientific_name('Anigozanthos flavidus').update(species: 'flavidus')
CurrentPlant.find_by_scientific_name('Brunfelsia pauciflora').update(species: 'pauciflora')
CurrentPlant.find_by_scientific_name('Verticordia nitens').update(species: 'nitens')
CurrentPlant.find_by_scientific_name('Bougainvillea glabra').update(species: 'glabra')
CurrentPlant.find_by_scientific_name('Astartea fascicularis').update(species: 'fascicularis')
CurrentPlant.find_by_scientific_name('Maireana oppositifolia').update(species: 'oppositifolia')
CurrentPlant.find_by_scientific_name('Rhagodia  spinescens var deltophylla').update(species: ' spinescens var deltophylla')
CurrentPlant.find_by_scientific_name('Verticordia monadelpha').update(species: 'monadelpha')
CurrentPlant.find_by_scientific_name('Nerium oleander cv pink Surprise').update(species: 'oleander cv pink Surprise')
CurrentPlant.find_by_scientific_name('Cordyline australis (inc)').update(species: 'australis ')
CurrentPlant.find_by_scientific_name('Banksia gardneri').update(species: 'gardneri')
CurrentPlant.find_by_scientific_name('Dietes bicolor').update(species: 'bicolor')
CurrentPlant.find_by_scientific_name('Dietes iridioides').update(species: 'iridioides')
CurrentPlant.find_by_scientific_name('Spinifex hirsutus').update(species: 'hirsutus')
CurrentPlant.find_by_scientific_name('Spinifex longifolia').update(species: 'longifolia')
CurrentPlant.find_by_scientific_name('Agapanthus praecox').update(species: 'praecox')
CurrentPlant.find_by_scientific_name('Banksia blechnifolia (incomplete)').update(species: 'blechnifolia ')
CurrentPlant.find_by_scientific_name('Banksia petiolaris').update(species: 'petiolaris')
CurrentPlant.find_by_scientific_name('Hibbertia huegelii').update(species: 'huegelii')
CurrentPlant.find_by_scientific_name('Correa alba').update(species: 'alba')
CurrentPlant.find_by_scientific_name('Guichenotia ledifolia').update(species: 'ledifolia')
CurrentPlant.find_by_scientific_name('Calothamnus hirsutus').update(species: 'hirsutus')
CurrentPlant.find_by_scientific_name('Acacia rostellifera').update(species: 'rostellifera')
CurrentPlant.find_by_scientific_name('Acacia truncata (incomplete)').update(species: 'truncata ')
CurrentPlant.find_by_scientific_name('Banksia ericifolia').update(species: 'ericifolia')
CurrentPlant.find_by_scientific_name('Cordyline indivisa').update(species: 'indivisa')
CurrentPlant.find_by_scientific_name('Cycad thouarsi').update(species: 'thouarsi')
CurrentPlant.find_by_scientific_name('Dodonea viscosa purpurea').update(species: 'viscosa purpurea')
CurrentPlant.find_by_scientific_name('Eucalyptus foecunda').update(species: 'foecunda')
CurrentPlant.find_by_scientific_name('Eucalyptus Lemanii').update(species: 'Lemanii')
CurrentPlant.find_by_scientific_name('Eucalyptus tetragona (incomplete)').update(species: 'tetragona ')
CurrentPlant.find_by_scientific_name('Grevillea crithmifolia').update(species: 'crithmifolia')
CurrentPlant.find_by_scientific_name('Grevillea nudiflora').update(species: 'nudiflora')
CurrentPlant.find_by_scientific_name('Grevillea olivacea [inc]').update(species: 'olivacea [inc]')
CurrentPlant.find_by_scientific_name('Juncus pallidus').update(species: 'pallidus')
CurrentPlant.find_by_scientific_name('Raphiolepis cv Apple Blossum').update(species: 'cv Apple Blossum')
CurrentPlant.find_by_scientific_name('Scaffold aneura').update(species: 'aneura')
CurrentPlant.find_by_scientific_name('Tecoma alata').update(species: 'alata')
CurrentPlant.find_by_scientific_name('Tetragona decumbens').update(species: 'decumbens')
CurrentPlant.find_by_scientific_name('Water hyacinth').update(species: 'hyacinth')
