puts "Seeding display photos..."

# 187 display photos
puts "  0/187"
CurrentPlant.find_by_scientific_name('zzz?').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/65D32C0D-28DD-41DA-BFD8-B984AE29F802.jpg"))
CurrentPlant.find_by_scientific_name('zzzA').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/5B7B8AC9-7924-4F5C-84AF-9C9095FC20EE.jpg"))
CurrentPlant.find_by_scientific_name('Acacia cyclops').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/acacia_cyclops_closeup.0.jpg"))
CurrentPlant.find_by_scientific_name('Acacia iteaphylla').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/acacia_iteaphylla_distance.0.jpg"))
CurrentPlant.find_by_scientific_name('Acacia lasiocarpa').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/acacia_lasiocarpa_flower.0.jpg"))
CurrentPlant.find_by_scientific_name('Acacia pulchella').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/E719C7AE-6A15-4874-BE1F-AD558BCD8F03.jpg"))
CurrentPlant.find_by_scientific_name('Acacia rostellifera').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/19DD0D4C-6116-472E-B874-A381AA427AD9.jpg"))
CurrentPlant.find_by_scientific_name('Acanthus mollis').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/acanthus_mollis_closeup.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Acmena smithii').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/acmena_smithii_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Adenanthos cygnorum').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/adenanthos_cygnorum_distance.0.jpg"))
CurrentPlant.find_by_scientific_name('Adenanthos sericeus').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/adenanthos_sericeus_distance.0.jpg"))
CurrentPlant.find_by_scientific_name('Agapanthus praecox').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/agapanthus_praecox_subsporientalis_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Agonis flexuosa').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/agonis_flexuosa_distance2.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Agonis flexuosa \'nana\'').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/agonis_flexuosa_distance2.1.jpg"))
CurrentPlant.find_by_scientific_name('Agonis linearifolia').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/agonis_linearifolia_distance.0.jpg"))
CurrentPlant.find_by_scientific_name('Ajuga reptans').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/ajuga_reptans_semicloseup.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Allocasuarina fraseriana').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/allocasuarina_fraseriana_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Andersonia gregoria').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/B85A741F-15A6-4F57-AF3F-B86F1F62BEA8.jpg"))
CurrentPlant.find_by_scientific_name('Angophora costata').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/angophora_costata_distance2.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Anigozanthos flavidus').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/anigozanthos_flavidus_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Anigozanthos manglesii').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/anigozanthos_manglesii_youngflower.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Anigozanthos viridus').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/anigozanthos_viridus_closeup.0.0.jpg"))
puts "  25/187"
CurrentPlant.find_by_scientific_name('Aptenia cordifolia').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/aptenia_cordifolia_closeup.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Araucaria heterophylla').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/araucaria_heterophylla_distance.1.0.jpg"))
CurrentPlant.find_by_scientific_name('Arctotis x hybrida').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/arctotis_x-hybrida_flower.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Aspidistra elatior').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/aspidistra_elatior_closeup.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Asplenium australasicum').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/asplenium_australasicum_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Astartea fascicularis').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/astartea_fascicularis_floweringdistance.0.jpg"))
CurrentPlant.find_by_scientific_name('Banksia ashbyi').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/D65B71E3-67E6-4556-9409-0D91A0FA4B8A.jpg"))
CurrentPlant.find_by_scientific_name('Banksia blechnifolia (incomplete)').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/C5738CAE-BECE-493C-B58F-B2FE38EC3705.jpg"))
CurrentPlant.find_by_scientific_name('Banksia grandis').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/banksia_grandis_closeup.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Banksia ilicifolia').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/banksia_ilicifolia_closeup.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Banksia menziesii').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/banksia_menziesii_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Banksia petiolaris').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/banksia_petiolaris_seed.0.jpg"))
CurrentPlant.find_by_scientific_name('Banksia prionotes').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/banksia_prionotes_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Beaufortia squarrosa').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/beaufortia_squarrosa_distance.0.jpg"))
CurrentPlant.find_by_scientific_name('Begonia').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/7BC536B8-469E-4C92-8A24-B9ABA456306B.jpg"))
CurrentPlant.find_by_scientific_name('Boronia crenulata').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/boronia_crenulata_distance.0.jpg"))
CurrentPlant.find_by_scientific_name('Boronia heterophylla').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/boronia_heterophylla_distance.0.jpg"))
CurrentPlant.find_by_scientific_name('Bougainvillea glabra').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/8AB7BA3A-601F-4A61-AB4E-2C13C78A8301.jpg"))
CurrentPlant.find_by_scientific_name('Brachychiton acerifolius').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/brachychiton_acerifolius_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Brachyscome iberidifolia').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/brachyscome_iberidifolia_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Brachyscome multifida').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/brachyscome_multifida_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Callistemon Little John').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/E17F3374-C477-4726-8E57-443A81AD38BC.jpg"))
CurrentPlant.find_by_scientific_name('Callistemon viminalis').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/callistemon_viminalis_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Callitris preissii').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/callitris_preissii_closeup.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Calodendron capense').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/59089DF4-1AC2-467B-B055-CAC0FF0D76BD.jpg"))
puts "  50/187"
CurrentPlant.find_by_scientific_name('Calothamnus hirsutus').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/ED2E0B91-3ECB-4243-9570-CF2163F4AC13.jpg"))
CurrentPlant.find_by_scientific_name('Calothamnus quadrifidus').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/calothamnus_quadrifidus_flower.0.jpg"))
CurrentPlant.find_by_scientific_name('Carpobrotus').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/688CB303-CA96-40DC-A621-AB5D343EEBBA.jpg"))
CurrentPlant.find_by_scientific_name('Carpobrotus glaucescens').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/carpobrotus_glaucescens_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Casuarina cunninghamiana').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/casuarina_cunninghamiana_semidistance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Casuarina equisetifolia').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/casuarina_equisetifolia_distance2.1.0.jpg"))
CurrentPlant.find_by_scientific_name('Casuarina obesa').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/casuarina_obesa_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Ceratoptalum gummiferum').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/B8957B6E-6FE6-4C26-A759-77D001FA911C.jpg"))
CurrentPlant.find_by_scientific_name('Chamelaucium ciliatum').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/chamelaucium_ciliatum_distance.0.jpg"))
CurrentPlant.find_by_scientific_name('Chamelaucium uncinatum').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/F27FBA94-E331-47B3-8D8B-68AAEE02E323.jpg"))
CurrentPlant.find_by_scientific_name('Chlorophytum comosum').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/chlorophytum_comosum_potted.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Chorizema cordatum').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/chorizema_cordatum_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Cinnamomum camphora').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/cinnamomum_camphora_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Clivia miniata').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/A68ECD98-6982-4CA8-B501-751FA194356D.jpg"))
CurrentPlant.find_by_scientific_name('Clivia nobilis').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/clivia_miniata_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Coleonema pulchrum').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/coleonema_pulchrum_distance.0.jpg"))
CurrentPlant.find_by_scientific_name('Conospermum stoechadis').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/conospermum_stoechadis_distance.0.jpg"))
CurrentPlant.find_by_scientific_name('Conostylis candicans').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/1CC9635A-CD11-4B44-8DAA-E56E1EA73598.jpg"))
CurrentPlant.find_by_scientific_name('Convolvulus sabatius').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/convolvulus_sabatius_flower2.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Coprosma repens').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/coprosma_repens_distance.0.jpg"))
CurrentPlant.find_by_scientific_name('Cordyline australis (inc)').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/cordyline_australis_ls.0.jpg"))
CurrentPlant.find_by_scientific_name('Correa alba').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/7D39398E-8611-4749-81C1-85EEEAE55F5D.jpg"))
CurrentPlant.find_by_scientific_name('Correa reflexa').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/correa_reflexa_flower.0.jpg"))
CurrentPlant.find_by_scientific_name('Corymbia calophylla').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/corymbia_calophylla_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Corymbia citriodora').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/corymbia_citriodora_distance.0.0.jpg"))
puts "  75/187"
CurrentPlant.find_by_scientific_name('Corymbia ficifolia').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/corymbia_ficifolia_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Corymbia maculata').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/corymbia_maculata_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Crinum pedunculatum').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/crinum_pedunculatum_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Cyathea cooperi').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/cyathea_cooperi_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Cycad thouarsi').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/23A33516-7DEB-410D-9171-40917C18E616.jpg"))
CurrentPlant.find_by_scientific_name('Cynodon dactylon').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/cynodon_dactylon_closeup.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Dampiera linearis').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/dampiera_linearis_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Darwinia citriodora').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/darwinia_citriodora_closeup.0.jpg"))
CurrentPlant.find_by_scientific_name('Delonix regia').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/delonix_regia_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Dianella revoluta').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/dianella_revoluta_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Dichondra repens').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/dichondra_repens_closeup.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Dietes bicolor').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/dietes_bicolor_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Dietes grandiflora').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/dietes_grandiflora_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Dodonea viscosa purpurea').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/9EE1052A-4F3C-4582-9220-7D78EF124F15.jpg"))
CurrentPlant.find_by_scientific_name('Dryandra nivea').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/dryandra_nivea_distance.0.jpg"))
CurrentPlant.find_by_scientific_name('Dryandra sessilis').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/dryandra_sessilis_distance.0.jpg"))
CurrentPlant.find_by_scientific_name('Eremophila ?').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/F36758A0-FE49-4B64-9A9F-0A29569DF4A3.jpg"))
CurrentPlant.find_by_scientific_name('Eremophila 2').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/9C6A3D9C-C54A-4728-960D-89969AE08488.jpg"))
CurrentPlant.find_by_scientific_name('Eremophila glabra').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/eremophila_glabra_closeup.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Eremophila nivea').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/eremophila_nivea_distance.0.jpg"))
CurrentPlant.find_by_scientific_name('Erythrina indica').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/erythrina_indica_deciduous2.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Eucalyptus camaldulensis').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/eucalyptus_camaldulensis_varcamaldulensis_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Eucalyptus cladocalyx').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/eucalyptus_cladocalyx_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Eucalyptus erythrocorys').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/eucalyptus_erythrocorys_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Eucalyptus foecunda').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/eucalyptus_foecunda_distanc.0.0.jpg"))
puts "  100/187"
CurrentPlant.find_by_scientific_name('Eucalyptus gomphocephala').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/eucalyptus_gomphocephala_semidistance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Eucalyptus Lemanii').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/3497A4E1-3F4E-46C4-801A-9703676BB66B.jpg"))
CurrentPlant.find_by_scientific_name('Eucalyptus leucoxylon').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/eucalyptus_leucoxylon_sspleucoxylon_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Eucalyptus macrocarpa').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/eucalyptus_macrocarpa_bud.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Eucalyptus marginata').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/eucalyptus_marginata_sspmarginata_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Eucalyptus sideroxylon').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/eucalyptus_sideroxylon_sspsideroxylon_closeup.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Ficinia nodosa').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/ficinia_nodosa_LS.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Ficus').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/849FAE96-22A9-4E9C-AED5-87660FC2810C.jpg"))
CurrentPlant.find_by_scientific_name('Ficus macrophylla').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/ficus_macrophylla_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Ficus pumila').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/ficus_pumila_closeup.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Gazania sp.').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/gazania_flower.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Ginkgo biloba').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/ginkgo_biloba_closeup.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Gleditsia tricanthos').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/gleditsia_tricanthos_distance3_tn.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Golden Cane Palm').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/8EFE1F98-511E-43A0-BE27-77D33B787D2E.jpg"))
CurrentPlant.find_by_scientific_name('Grevilea').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/468916CE-DF9C-4233-AB43-4285672FB34E.jpg"))
CurrentPlant.find_by_scientific_name('Grevillea').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/BBD9162A-1DCA-4E43-A10C-0E3313C823C7.jpg"))
#CurrentPlant.find_by_scientific_name('Grevillea ').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/10F3841C-88FB-4830-AA77-579CE6ADF64F.jpg"))
CurrentPlant.find_by_scientific_name('Grevillea crithmifolia').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/grevillea_crithmifolia_ls.0.jpg"))
CurrentPlant.find_by_scientific_name('Grevillea obtusifolia').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/grevillea_obtusifolia_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Grevillea olivacea [inc]').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/grevillea_olivacea_distance.0.jpg"))
CurrentPlant.find_by_scientific_name('Guichenotia ledifolia').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/8A795864-0011-40E5-82F6-513F7D63B762.jpg"))
CurrentPlant.find_by_scientific_name('Hake 2').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/1C3E4BD1-14CF-46B4-A6F3-8223E4534E1E.jpg"))
CurrentPlant.find_by_scientific_name('Hake 1').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/D6BDB035-07D1-4D60-8548-C651766F6F8E.jpg"))
CurrentPlant.find_by_scientific_name('Hakea laurina').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/AE14C109-A290-4D08-8FFD-AD32D3839D83.jpg"))
CurrentPlant.find_by_scientific_name('Hardenbergia comptoniana').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/C5755620-5C71-49FE-98BE-38CBDAC472A6.jpg"))
puts "  125/187"
CurrentPlant.find_by_scientific_name('Hedera canariensis').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/hedera_canariensis_climbing.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Hemiandra pungens').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/hemiandra_pungens_flower.0.jpg"))
CurrentPlant.find_by_scientific_name('Hibbertia cuneiformis').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/299BAB7A-83C8-4797-8DF9-6AF7BD1003F6.jpg"))
CurrentPlant.find_by_scientific_name('Hibbertia huegelii').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/4C544A95-5BCF-4AB9-8D65-74A0CFB51B66.jpg"))
CurrentPlant.find_by_scientific_name('Hibiscus').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/581C5183-3853-48FE-A51F-37C604BBAEAD.jpg"))
CurrentPlant.find_by_scientific_name('Hymenosporum flavum').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/hymenosporum_flavum_flower2.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Hypocalyma').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/C7E6F60A-2AAD-4AF1-A01B-EB627C11455F.jpg"))
CurrentPlant.find_by_scientific_name('Isopogon').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/D6AF3745-C555-4984-9181-194506B8EDCC.jpg"))
CurrentPlant.find_by_scientific_name('Jacaranda mimosifolia').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/6D99DD63-54A9-4415-900E-18F60CBB8150.jpg"))
CurrentPlant.find_by_scientific_name('Juncus karusii (incomplete)').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/juncus_krausii_distance2.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Juncus pallidus').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/juncus_pallidus_LS.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Lechenaultia biloba').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/08BCF27B-9AC5-4A21-B38A-BE9502A3A286.jpg"))
CurrentPlant.find_by_scientific_name('Lepidosperma gladiatum').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/lepidosperma_gladiatum_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Leucophyta brownii').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/leucophyta_brownii_semidistance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Leucospermum').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/B815B23F-7AE5-4B71-9A6E-3B7104317367.jpg"))
CurrentPlant.find_by_scientific_name('Liquidamber styraciflua (incomplete)').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/75374FBD-4BD7-44BF-8F48-2909BFDCB5D4.jpg"))
CurrentPlant.find_by_scientific_name('Lobelia alata').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/lobelia_alata_flower.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Lomandra longifolia').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/lomandra_longifolia_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Maireana oppositifolia').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/89394F2F-8D06-4933-986B-01AD5E560BA5.jpg"))
CurrentPlant.find_by_scientific_name('Mandevilla').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/BCAF5CB6-0A88-4C47-BE83-E950E7609AA2.jpg"))
CurrentPlant.find_by_scientific_name('Melaleuca').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/F6A67220-E37C-4AA0-B2A9-5274DCB94BAE.jpg"))
CurrentPlant.find_by_scientific_name('Melaleuca huegelii').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/0D9F5D9C-945A-4608-AD70-47B981CD22D0.jpg"))
CurrentPlant.find_by_scientific_name('Melaleuca nesophila').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/melaleuca_nesophilla_flower.0.jpg"))
CurrentPlant.find_by_scientific_name('Melia azedarach var. australasica (incomplete)').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/DAEC4D55-CB93-4EC9-A68E-F4E701481A59.jpg"))
CurrentPlant.find_by_scientific_name('Myoporum parvifolium').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/Myoporum parvifolium  WP.0.0.JPG"))
puts "  150/187"
CurrentPlant.find_by_scientific_name('Nerium oleander cv pink Surprise').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/AEA93828-4273-4150-8776-836F3DF0399D.jpg"))
CurrentPlant.find_by_scientific_name('Olearia axillaris').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/olearia_axillaris_distance3.0.jpg"))
CurrentPlant.find_by_scientific_name('Pandanas').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/B3903FF1-0B97-4F6F-B461-DA61A60B348F.jpg"))
CurrentPlant.find_by_scientific_name('Parthenocissus quiniquefolia (incomplete)').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/parthenocissus_quinquefolia_leaves.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Parthenocissus tricuspidata (incomplete)').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/parthenocissus_tricuspida_leaves.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Pelargonium').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/6728E323-B749-474B-9406-ACA2A2C48321.jpg"))
CurrentPlant.find_by_scientific_name('Phoenix roebelenii').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/phoenix_roebelenii_distance.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Pilots exaltatus').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/938C7278-1ABF-46FD-98ED-5473EBB65622.jpg"))
CurrentPlant.find_by_scientific_name('Pimelea').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/6C43FAEB-2927-4255-9ABB-D27972E5DFF5.jpg"))
CurrentPlant.find_by_scientific_name('Pimelea ferruginea').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/pimelea_ferruginea_wholeplant.0.jpg"))
CurrentPlant.find_by_scientific_name('Pittosporum rhombifolium (incomplete)').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/pittosporum_rhombifolium_fruit.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Plantanus x acerfolia').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/CEC37F4F-4AA9-4BB7-824D-B12D18D64C16.jpg"))
CurrentPlant.find_by_scientific_name('Plumeria').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/8009C57F-918D-492D-AD2F-A416855BB758.jpg"))
CurrentPlant.find_by_scientific_name('Raphiolepis cv Apple Blossum').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/5369CC67-5E23-456B-9290-9013B625D10E.jpg"))
CurrentPlant.find_by_scientific_name('Raphiolepis indica').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/raphiolepis_indica_flowe.0.jpg"))
CurrentPlant.find_by_scientific_name('Regalia?').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/8A5B5F25-07EE-4EA5-9B25-FA28272C2FD6.jpg"))
CurrentPlant.find_by_scientific_name('Rhagodia  spinescens var deltophylla').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/9B0B61F8-1B29-4DB0-97A3-6B922A9FDA13.jpg"))
CurrentPlant.find_by_scientific_name('Ricinocarpus tuberculatus x cyanescens').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/8CB12373-DF82-4168-A025-0C8BEBF9693E.jpg"))
CurrentPlant.find_by_scientific_name('Robinia pseudoacacia').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/641237DB-E2A1-4E5C-BE78-7494DAA203EC.jpg"))
CurrentPlant.find_by_scientific_name('Sapium sebiferum (incomplete)').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/sapium_sebiferum_closeup.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Scaevola \'Purple Fanfare\' (incomplete)').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/scaevola_purple_fanfare_close.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Scaffold aneura').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/F8E8EDB5-C1B1-400B-AB60-85737B3FA212.jpg"))
CurrentPlant.find_by_scientific_name('Spinifex longifolia').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/BEDD9C20-0DDD-4801-AD94-2DCFFE36CB6E.jpg"))
CurrentPlant.find_by_scientific_name('Swainsona').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/2FD3FF72-927D-4AAE-9414-A5A2EEA56E2C.jpg"))
CurrentPlant.find_by_scientific_name('Tecoma alata').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/AAD1382C-FE37-4DB2-8CC1-F44019623A4E.jpg"))
puts "  175/187"
CurrentPlant.find_by_scientific_name('Templetonia retusa').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/templetonia_retusa_WP.0.jpg"))
CurrentPlant.find_by_scientific_name('Tetragona decumbens').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/3119E737-A323-4E69-9DAB-6103FC4D6746.jpg"))
CurrentPlant.find_by_scientific_name('Thryptomene saxicola (incomplete)').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/thryptomene_saxicola_flower.0.jpg"))
CurrentPlant.find_by_scientific_name('Tipuana tipu').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/tipuana_tipu_distance2.0.0.jpg"))
CurrentPlant.find_by_scientific_name('Unknown 3').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/C55A1777-AAA8-4468-92B5-E288C7E6F0CE.jpg"))
CurrentPlant.find_by_scientific_name('Unknown 2').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/DBB06C11-4F32-4F50-B56D-1F21A38F3021.jpg"))
CurrentPlant.find_by_scientific_name('Unknown1').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/AF5F10B1-ABAC-411C-BFBA-150EFE9EFC38.jpg"))
CurrentPlant.find_by_scientific_name('Verticordia').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/76E72711-9880-48D7-B873-73C15F4A2FBE.jpg"))
CurrentPlant.find_by_scientific_name('Verticordia nitens').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/688183E6-398A-4E1F-9078-D88FBC80BEF1.jpg"))
CurrentPlant.find_by_scientific_name('Viburnum?').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/B3EE08F5-09CE-405A-8998-50258450F380.jpg"))
CurrentPlant.find_by_scientific_name('Water hyacinth').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/C91A1619-E32D-495B-BB89-8B8254EA1B3A.jpg"))
CurrentPlant.find_by_scientific_name('Westringia fruiticosa').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/Westringia_fruiticosa_ls.0.jpg"))
CurrentPlant.find_by_scientific_name('Wollemia nobilis').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/C779664C-EC9F-46AE-8D1B-F266C53FFF62.jpg"))
CurrentPlant.find_by_scientific_name('Yellow Broome').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/307BBD15-D933-4F2C-A1F2-DCB641EC956A.jpg"))
CurrentPlant.find_by_scientific_name('Zamia furfuracea').update(display_photo: File.open("#{Rails.root}/lib/tasks/sample_photos/CF0D6AAF-00DE-4DFD-AC1E-036DBCF63D16.jpg"))