puts 'Seeding Soil Types...'

@quin = SoilType.create(name: 'Quindalup') 
@cott = SoilType.create(name: 'Cottesloe') 
@karr = SoilType.create(name: 'Karrakatta') 
@guil = SoilType.create(name: 'Guildford') 
@bass = SoilType.create(name: 'Bassendean') 
@beer = SoilType.create(name: 'Beermullah') 
@forr = SoilType.create(name: 'Forrestfield') 
@herd = SoilType.create(name: 'Herdsman') 
@swan = SoilType.create(name: 'Swan Vasse') 
@dard = SoilType.create(name: 'Dardanup Darling Plateau') 
@gran = SoilType.create(name: 'Granite Darling Plateau') 
@late = SoilType.create(name: 'Laterite Dalring Plateau') 
@scar = SoilType.create(name: 'Scarp Darling Plateau') 
@yang = SoilType.create(name: 'Yanga') 
@serp = SoilType.create(name: 'Serpentine River')

@quin.current_plants << CurrentPlant.find_by_scientific_name('Robinia pseudoacacia')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca viridiflora (incomplete)')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Banksia attenuata')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Raphiolepis indica')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus oxycarpa cv \'Raywood\' (Incomplete)')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus excelsior (Incomplete)')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Conospermum stoechadis')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Acacia saligna')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Dryandra nivea')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Leucophyta brownii')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Hibbertia cuneiformis')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Acacia lasiocarpa')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca pentagona')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Chamelaucium uncinatum')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Conostylis candicans')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Dichondra repens')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Ficinia nodosa')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Carpobrotus virescens')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Hardenbergia comptoniana')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Calothamnus quadrifidus')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Murraya paniculata')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Dryandra sessilis')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Agonis flexuosa')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Pittosporum rhombifolium (incomplete)')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Acacia cyclops')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Callitris preissii')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca lanceolata')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Hemiandra pungens')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Grevillea preisii \'Grevillea thelemanniana')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Dianella revoluta')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Banksia littoralis')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Hypocalymma robustum')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Eremophila glabra')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Eucalyptus gomphocephala')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Ricinocarpus tuberculatus x cyanescens')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Baeckea virgata (inc)')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Grevillea crithmifolia')
@quin.current_plants << CurrentPlant.find_by_scientific_name('Grevillea nudiflora')


@cott.current_plants << CurrentPlant.find_by_scientific_name('Boronia crenulata')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Robinia pseudoacacia')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca viridiflora (incomplete)')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Banksia grandis')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Banksia attenuata')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Raphiolepis indica')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus oxycarpa cv \'Raywood\' (Incomplete)')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus excelsior (Incomplete)')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Dampiera linearis')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Allocasuarina fraseriana')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Conospermum stoechadis')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Acacia saligna')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Dryandra nivea')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Leucophyta brownii')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Hovea pungens')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Acacia lasiocarpa')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca pentagona')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Chamelaucium uncinatum')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Conostylis candicans')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Eucalyptus marginata')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Dichondra repens')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Ficinia nodosa')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Corymbia calophylla')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Banksia menziesii')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Carpobrotus virescens')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Hardenbergia comptoniana')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Calothamnus quadrifidus')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Eremaea pauciflora')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Murraya paniculata')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Dryandra sessilis')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Agonis flexuosa')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Acacia cyclops')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Callitris preissii')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca cuticularis')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Hemiandra pungens')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Grevillea preisii \'Grevillea thelemanniana')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Dianella revoluta')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Brachyscome iberidifolia')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Eremophila glabra')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Eucalyptus gomphocephala')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Baeckea virgata (inc)')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Acacia xanthina')
@cott.current_plants << CurrentPlant.find_by_scientific_name('Grevillea crithmifolia')

@karr.current_plants << CurrentPlant.find_by_scientific_name('Boronia crenulata')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Robinia pseudoacacia')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Lechenaultia biloba')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca viridiflora (incomplete)')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Banksia grandis')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Banksia attenuata')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Raphiolepis indica')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus oxycarpa cv \'Raywood\' (Incomplete)')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus excelsior (Incomplete)')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Dampiera linearis')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Allocasuarina fraseriana')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Conospermum stoechadis')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Adenanthos cygnorum')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Acacia saligna')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Dryandra nivea')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Hovea pungens')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Acacia lasiocarpa')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca pentagona')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Hedera helix')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Conostylis candicans')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Banksia ilicifolia')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Parthenocissus tricuspidata (incomplete)')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Eucalyptus marginata')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Ficinia nodosa')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Corymbia calophylla')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Banksia menziesii')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Hardenbergia comptoniana')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Calothamnus quadrifidus')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Eremaea pauciflora')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Murraya paniculata')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Dryandra sessilis')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Pittosporum rhombifolium (incomplete)')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Acacia cyclops')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Banksia prionotes')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Hemiandra pungens')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Grevillea preisii \'Grevillea thelemanniana')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Dianella revoluta')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Hypocalymma robustum')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Eremophila glabra')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Eucalyptus gomphocephala')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Ricinocarpus tuberculatus x cyanescens')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Baeckea virgata (inc)')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Guichenotia ledifolia')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Grevillea crithmifolia')
@karr.current_plants << CurrentPlant.find_by_scientific_name('Grevillea nudiflora')

@guil.current_plants << CurrentPlant.find_by_scientific_name('Robinia pseudoacacia')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Lechenaultia biloba')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca viridiflora (incomplete)')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Banksia grandis')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Baeckea camphorosmae')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Banksia attenuata')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Raphiolepis indica')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus oxycarpa cv \'Raywood\' (Incomplete)')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus excelsior (Incomplete)')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Dampiera linearis')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Allocasuarina fraseriana')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Conospermum stoechadis')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Adenanthos cygnorum')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Acacia saligna')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Dryandra nivea')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Hovea pungens')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Acacia lasiocarpa')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca pentagona')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Eucalyptus rudis')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Conostylis candicans')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Banksia ilicifolia')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Parthenocissus tricuspidata (incomplete)')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Ficinia nodosa')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Corymbia calophylla')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Banksia menziesii')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Hardenbergia comptoniana')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Calothamnus quadrifidus')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Eremaea pauciflora')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Murraya paniculata')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Dryandra sessilis')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Pittosporum rhombifolium (incomplete)')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Casuarina obesa')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca cuticularis')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Beaufortia squarrosa')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Hemiandra pungens')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Grevillea thelemanniana')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Grevillea preisii \'Grevillea thelemanniana')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Dianella revoluta')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Banksia littoralis')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Agonis linearifolia')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Brachyscome iberidifolia')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Hypocalymma robustum')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Eremophila glabra')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Eucalyptus wandoo')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Ricinocarpus tuberculatus x cyanescens')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Baeckea virgata (inc)')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Astartea fascicularis')
@guil.current_plants << CurrentPlant.find_by_scientific_name('Grevillea nudiflora')

@bass.current_plants << CurrentPlant.find_by_scientific_name('Boronia crenulata')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Robinia pseudoacacia')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca viridiflora (incomplete)')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Banksia grandis')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Baeckea camphorosmae')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Banksia attenuata')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Raphiolepis indica')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus oxycarpa cv \'Raywood\' (Incomplete)')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus excelsior (Incomplete)')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Dampiera linearis')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Allocasuarina fraseriana')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Conospermum stoechadis')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Adenanthos cygnorum')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Acacia saligna')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Dryandra nivea')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Hovea pungens')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Acacia lasiocarpa')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca pentagona')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Eucalyptus rudis')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Conostylis candicans')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Banksia ilicifolia')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Eucalyptus marginata')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Ficinia nodosa')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Corymbia calophylla')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Banksia menziesii')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Hardenbergia comptoniana')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Calothamnus quadrifidus')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Eremaea pauciflora')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Murraya paniculata')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Juncus karusii (incomplete)')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Hemiandra pungens')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Dianella revoluta')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Banksia littoralis')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Agonis linearifolia')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Brachyscome iberidifolia')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Hypocalymma robustum')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Ricinocarpus tuberculatus x cyanescens')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Baeckea virgata (inc)')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Astartea fascicularis')
@bass.current_plants << CurrentPlant.find_by_scientific_name('Grevillea nudiflora')

@beer.current_plants << CurrentPlant.find_by_scientific_name('Robinia pseudoacacia')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca viridiflora (incomplete)')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Baeckea camphorosmae')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Banksia attenuata')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Raphiolepis indica')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus oxycarpa cv \'Raywood\' (Incomplete)')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus excelsior (Incomplete)')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Dampiera linearis')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Conospermum stoechadis')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Adenanthos cygnorum')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Acacia saligna')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Dryandra nivea')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Acacia lasiocarpa')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca pentagona')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Eucalyptus rudis')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Ficinia nodosa')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Corymbia calophylla')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Banksia menziesii')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Eremaea pauciflora')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Murraya paniculata')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Casuarina obesa')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Beaufortia squarrosa')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Hemiandra pungens')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Brachyscome iberidifolia')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Hypocalymma robustum')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Ricinocarpus tuberculatus x cyanescens')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Baeckea virgata (inc)')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Astartea fascicularis')
@beer.current_plants << CurrentPlant.find_by_scientific_name('Grevillea nudiflora')

@forr.current_plants << CurrentPlant.find_by_scientific_name('Robinia pseudoacacia')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Lechenaultia biloba')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca viridiflora (incomplete)')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Banksia grandis')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Baeckea camphorosmae')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Banksia attenuata')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Raphiolepis indica')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus oxycarpa cv \'Raywood\' (Incomplete)')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus excelsior (Incomplete)')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Dampiera linearis')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Allocasuarina fraseriana')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Conospermum stoechadis')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Adenanthos cygnorum')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Acacia saligna')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Dryandra nivea')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Hovea pungens')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Acacia lasiocarpa')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca pentagona')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Chorizema cordatum')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Banksia ilicifolia')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Ficinia nodosa')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Corymbia calophylla')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Banksia menziesii')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Hardenbergia comptoniana')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Calothamnus quadrifidus')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Eremaea pauciflora')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Murraya paniculata')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Dryandra sessilis')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Pittosporum rhombifolium (incomplete)')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Hemiandra pungens')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Grevillea preisii \'Grevillea thelemanniana')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Dianella revoluta')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Banksia littoralis')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Brachyscome iberidifolia')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Hypocalymma robustum')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Ricinocarpus tuberculatus x cyanescens')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Baeckea virgata (inc)')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Astartea fascicularis')
@forr.current_plants << CurrentPlant.find_by_scientific_name('Grevillea nudiflora')

@herd.current_plants << CurrentPlant.find_by_scientific_name('Robinia pseudoacacia')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Lechenaultia biloba')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca viridiflora (incomplete)')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Raphiolepis indica')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus oxycarpa cv \'Raywood\' (Incomplete)')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus excelsior (Incomplete)')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Dampiera linearis')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Acacia saligna')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Acacia lasiocarpa')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca pentagona')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Eucalyptus rudis')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Banksia ilicifolia')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Ficinia nodosa')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Corymbia calophylla')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Murraya paniculata')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Pittosporum rhombifolium (incomplete)')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Acacia cyclops')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Juncus karusii (incomplete)')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Dianella revoluta')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Banksia littoralis')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Brachyscome iberidifolia')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Hypocalymma robustum')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Eucalyptus gomphocephala')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Ricinocarpus tuberculatus x cyanescens')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Baeckea virgata (inc)')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Astartea fascicularis')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Grevillea nudiflora')
@herd.current_plants << CurrentPlant.find_by_scientific_name('Juncus pallidus')

@dard.current_plants << CurrentPlant.find_by_scientific_name('Robinia pseudoacacia')
@dard.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca viridiflora (incomplete)')
@dard.current_plants << CurrentPlant.find_by_scientific_name('Raphiolepis indica')
@dard.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus oxycarpa cv \'Raywood\' (Incomplete)')
@dard.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus excelsior (Incomplete)')
@dard.current_plants << CurrentPlant.find_by_scientific_name('Acacia saligna')
@dard.current_plants << CurrentPlant.find_by_scientific_name('Acacia lasiocarpa')
@dard.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca pentagona')
@dard.current_plants << CurrentPlant.find_by_scientific_name('Ficinia nodosa')
@dard.current_plants << CurrentPlant.find_by_scientific_name('Murraya paniculata')
@dard.current_plants << CurrentPlant.find_by_scientific_name('Pittosporum rhombifolium (incomplete)')
@dard.current_plants << CurrentPlant.find_by_scientific_name('Grevillea preisii \'Grevillea thelemanniana')
@dard.current_plants << CurrentPlant.find_by_scientific_name('Hypocalymma robustum')
@dard.current_plants << CurrentPlant.find_by_scientific_name('Ricinocarpus tuberculatus x cyanescens')
@dard.current_plants << CurrentPlant.find_by_scientific_name('Baeckea virgata (inc)')
@dard.current_plants << CurrentPlant.find_by_scientific_name('Grevillea nudiflora')

@gran.current_plants << CurrentPlant.find_by_scientific_name('Robinia pseudoacacia')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Lechenaultia biloba')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca viridiflora (incomplete)')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Baeckea camphorosmae')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Raphiolepis indica')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus oxycarpa cv \'Raywood\' (Incomplete)')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus excelsior (Incomplete)')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Acacia saligna')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Dryandra nivea')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Hovea pungens')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Acacia lasiocarpa')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca pentagona')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Ficinia nodosa')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Darwinia citriodora')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Corymbia calophylla')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Calothamnus quadrifidus')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Murraya paniculata')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Pittosporum rhombifolium (incomplete)')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Hakea petiolaris')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Grevillea preisii \'Grevillea thelemanniana')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Dianella revoluta')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Hypocalymma robustum')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Eucalyptus wandoo')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Ricinocarpus tuberculatus x cyanescens')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Baeckea virgata (inc)')
@gran.current_plants << CurrentPlant.find_by_scientific_name('Grevillea nudiflora')

@late.current_plants << CurrentPlant.find_by_scientific_name('Boronia crenulata')
@late.current_plants << CurrentPlant.find_by_scientific_name('Robinia pseudoacacia')
@late.current_plants << CurrentPlant.find_by_scientific_name('Lechenaultia biloba')
@late.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca viridiflora (incomplete)')
@late.current_plants << CurrentPlant.find_by_scientific_name('Banksia grandis')
@late.current_plants << CurrentPlant.find_by_scientific_name('Baeckea camphorosmae')
@late.current_plants << CurrentPlant.find_by_scientific_name('Banksia attenuata')
@late.current_plants << CurrentPlant.find_by_scientific_name('Raphiolepis indica')
@late.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus oxycarpa cv \'Raywood\' (Incomplete)')
@late.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus excelsior (Incomplete)')
@late.current_plants << CurrentPlant.find_by_scientific_name('Allocasuarina fraseriana')
@late.current_plants << CurrentPlant.find_by_scientific_name('Adenanthos cygnorum')
@late.current_plants << CurrentPlant.find_by_scientific_name('Acacia saligna')
@late.current_plants << CurrentPlant.find_by_scientific_name('Dryandra nivea')
@late.current_plants << CurrentPlant.find_by_scientific_name('Acacia lasiocarpa')
@late.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca pentagona')
@late.current_plants << CurrentPlant.find_by_scientific_name('Ficinia nodosa')
@late.current_plants << CurrentPlant.find_by_scientific_name('Corymbia calophylla')
@late.current_plants << CurrentPlant.find_by_scientific_name('Murraya paniculata')
@late.current_plants << CurrentPlant.find_by_scientific_name('Dryandra sessilis')
@late.current_plants << CurrentPlant.find_by_scientific_name('Pittosporum rhombifolium (incomplete)')
@late.current_plants << CurrentPlant.find_by_scientific_name('Hemiandra pungens')
@late.current_plants << CurrentPlant.find_by_scientific_name('Grevillea preisii \'Grevillea thelemanniana')
@late.current_plants << CurrentPlant.find_by_scientific_name('Dianella revoluta')
@late.current_plants << CurrentPlant.find_by_scientific_name('Hypocalymma robustum')
@late.current_plants << CurrentPlant.find_by_scientific_name('Ricinocarpus tuberculatus x cyanescens')
@late.current_plants << CurrentPlant.find_by_scientific_name('Baeckea virgata (inc)')
@late.current_plants << CurrentPlant.find_by_scientific_name('Hibbertia huegelii')
@late.current_plants << CurrentPlant.find_by_scientific_name('Grevillea nudiflora')

@scar.current_plants << CurrentPlant.find_by_scientific_name('Boronia crenulata')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Robinia pseudoacacia')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Lechenaultia biloba')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca viridiflora (incomplete)')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Baeckea camphorosmae')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Raphiolepis indica')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus oxycarpa cv \'Raywood\' (Incomplete)')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus excelsior (Incomplete)')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Allocasuarina fraseriana')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Conospermum stoechadis')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Adenanthos cygnorum')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Acacia saligna')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Dryandra nivea')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Hovea pungens')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Acacia lasiocarpa')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca pentagona')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Callistemon phoeniceus')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Eucalyptus rudis')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Conostylis candicans')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Chorizema cordatum')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Parthenocissus tricuspidata (incomplete)')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Ficinia nodosa')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Darwinia citriodora')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Corymbia calophylla')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Calothamnus quadrifidus')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Eremaea pauciflora')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Murraya paniculata')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Dryandra sessilis')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Pittosporum rhombifolium (incomplete)')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Hakea petiolaris')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Hemiandra pungens')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Grevillea preisii \'Grevillea thelemanniana')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Dianella revoluta')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Agonis linearifolia')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Hypocalymma robustum')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Eucalyptus wandoo')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Ricinocarpus tuberculatus x cyanescens')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Baeckea virgata (inc)')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Astartea fascicularis')
@scar.current_plants << CurrentPlant.find_by_scientific_name('Grevillea nudiflora')

@yang.current_plants << CurrentPlant.find_by_scientific_name('Robinia pseudoacacia')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca viridiflora (incomplete)')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Raphiolepis indica')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus oxycarpa cv \'Raywood\' (Incomplete)')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus excelsior (Incomplete)')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Dampiera linearis')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Adenanthos cygnorum')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Acacia saligna')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Dryandra nivea')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Acacia lasiocarpa')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca pentagona')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Eucalyptus rudis')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Ficinia nodosa')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Corymbia calophylla')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Banksia menziesii')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Murraya paniculata')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Pittosporum rhombifolium (incomplete)')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Grevillea preisii \'Grevillea thelemanniana')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Brachyscome iberidifolia')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Hypocalymma robustum')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Eremophila glabra')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Ricinocarpus tuberculatus x cyanescens')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Baeckea virgata (inc)')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Astartea fascicularis')
@yang.current_plants << CurrentPlant.find_by_scientific_name('Grevillea nudiflora')

@serp.current_plants << CurrentPlant.find_by_scientific_name('Robinia pseudoacacia')
@serp.current_plants << CurrentPlant.find_by_scientific_name('Lechenaultia biloba')
@serp.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca viridiflora (incomplete)')
@serp.current_plants << CurrentPlant.find_by_scientific_name('Raphiolepis indica')
@serp.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus oxycarpa cv \'Raywood\' (Incomplete)')
@serp.current_plants << CurrentPlant.find_by_scientific_name('Fraxinus excelsior (Incomplete)')
@serp.current_plants << CurrentPlant.find_by_scientific_name('Acacia saligna')
@serp.current_plants << CurrentPlant.find_by_scientific_name('Acacia lasiocarpa')
@serp.current_plants << CurrentPlant.find_by_scientific_name('Melaleuca pentagona')
@serp.current_plants << CurrentPlant.find_by_scientific_name('Ficinia nodosa')
@serp.current_plants << CurrentPlant.find_by_scientific_name('Murraya paniculata')
@serp.current_plants << CurrentPlant.find_by_scientific_name('Pittosporum rhombifolium (incomplete)')
@serp.current_plants << CurrentPlant.find_by_scientific_name('Juncus karusii (incomplete)')
@serp.current_plants << CurrentPlant.find_by_scientific_name('Grevillea preisii \'Grevillea thelemanniana')
@serp.current_plants << CurrentPlant.find_by_scientific_name('Hypocalymma robustum')
@serp.current_plants << CurrentPlant.find_by_scientific_name('Ricinocarpus tuberculatus x cyanescens')
@serp.current_plants << CurrentPlant.find_by_scientific_name('Baeckea virgata (inc)')
@serp.current_plants << CurrentPlant.find_by_scientific_name('Grevillea nudiflora')